const products = [
    {
        id: 1,
        slug: "crochet-cuddly-bunny",
        name: "Crochet Cuddly Bunny",
        price: 14.0,
        image: "/assets/bunny.png",
        colors: ["#FFB6C1", "#87CEEB", "#90EE90"],
        badge: null,
    },
    {
        id: 2,
        slug: "crochet-bear",
        name: "Crochet Bear",
        price: 15.0,
        image: "/assets/Croche Bear.png",
        colors: ["#FF6B6B", "#4ECDC4", "#45B7D1"],
        badge: null,
    },
    {
        id: 3,
        slug: "crochet-hippo",
        name: "Crochet Hippo",
        price: 10.0,
        originalPrice: 16.0,
        image: "/assets/Crochet Bunny with a Bow.png",
        colors: ["#FFE4B5", "#E6E6FA", "#F0E68C"],
        badge: "Sale 5%",
    },
    {
        id: 4,
        slug: "crochet-bunny-with-a-bow",
        name: "Crochet Bunny with a Bow",
        price: 12.0,
        originalPrice: 16.0,
        image: "/assets/Crochet Hippo.png",
        colors: ["#DDA0DD", "#F0E68C", "#98FB98"],
        badge: "Sale 5%",
    },
    {
        id: 5,
        slug: "crochet-mouse-with-a-hat",
        name: "Crochet Mouse with a Hat",
        price: 18.0,
        image: "/assets/Crochet Little Llama.png",
        colors: ["#8B4513", "#4682B4", "#32CD32", "#FFD700"],
        badge: null,
    },
    {
        id: 6,
        slug: "crochet-unicorn",
        name: "Crochet Unicorn",
        price: 19.0,
        image: "/assets/Crochet Mouse with a Hat.png",
        colors: ["#87CEEB", "#FFB6C1", "#FFFFE0"],
        badge: null,
    },
    {
        id: 7,
        slug: "crochet-little-llama",
        name: "Crochet Little Llama",
        price: 16.0,
        originalPrice: 20.0,
        image: "/assets/Crochet Round Elephant.png",
        colors: ["#87CEEB", "#F0E68C", "#90EE90"],
        badge: "Sale 5%",
    },
    {
        id: 8,
        slug: "crochet-round-elephant",
        name: "Crochet Round Elephant",
        price: 17.0,
        originalPrice: 22.0,
        image: "/assets/Crochet Unicorn.png",
        colors: ["#E6E6FA", "#DDA0DD", "#F0E68C"],
        badge: "Sale 5%",
    },
];
export default products;
